name: Deploy to A2 Hosting

on:
  push:
    branches:
      - main  # or 'master' or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.A2_HOST }}
          username: ${{ secrets.A2_USER }}
          key: ${{ secrets.A2_SSH_KEY }}
          script: |
            cd ~/nodeapps/myapp
            git pull origin main
            npm install
            touch tmp/restart.txt
