name: Deploy to A2 Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.A2_SSH_HOST }}
          username: ${{ secrets.A2_SSH_USER }}
          key: ${{ secrets.A2_SSH_KEY }}
          passphrase: ${{ secrets.A2_SSH_PASSPHRASE }}
          port: 7822
          script: |
            cd /home/wingslidecoin/githubflowtest
            
            # Remove node_modules if it exists
            if [ -d "node_modules" ]; then
              echo "Removing node_modules directory"
              rm -rf node_modules
            fi

            git pull origin main
            npm install --production
            ~/nodevenv/githubflowtest/20/bin/restart